#!/usr/bin/env python3
"""
multica_omp_wrapper.py

Single drop-in replacement for the three bash `exec omp ...` shims Multica
calls (multica-omp-smol / multica-omp-reasoning / multica-omp-coding).

Responsibilities:
  1. Work out which of the three runtime profiles it's playing (via argv[0],
     an env var, or an explicit flag) and build the matching omp flag set.
  2. Log every invocation (args + session id + profile) for debugging.
  3. Fix CLAUDE.md being shadowed by Multica's auto-generated AGENTS.md:
     merge AGENTS.md into CLAUDE.md under a marked, idempotent block, then
     hide AGENTS.md as AGENTS.md.ignored so omp/CLAUDE-based tooling only
     sees CLAUDE.md. Restore AGENTS.md when omp exits (success, failure, or
     signal) via atexit + signal handlers, with self-healing on next run in
     case the process is SIGKILL'd and cleanup never fires.
  4. (Experimental — see README below) warn / optionally signal when a
     resumed session's jsonl is large enough it should probably be
     compacted first.

Deploy by creating three symlinks (or hardlinks/copies) that all point here:

    ln -s /path/to/multica_omp_wrapper.py /usr/local/bin/multica-omp-smol
    ln -s /path/to/multica_omp_wrapper.py /usr/local/bin/multica-omp-reasoning
    ln -s /path/to/multica_omp_wrapper.py /usr/local/bin/multica-omp-coding
    chmod +x /path/to/multica_omp_wrapper.py

Then point Multica's per-role runtime config at the symlink names exactly
like it currently points at the bash shims. No other Multica-side change
is required — all of Multica's own flags (-p, --mode, --session, --provider,
--model, and the trailing prompt) are forwarded untouched.
"""

from __future__ import annotations

import argparse
import atexit
import json
import os
import shutil
import signal
import subprocess
import sys
import time
import uuid
from pathlib import Path

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

OMP_BIN = os.environ.get("MULTICA_OMP_BIN", "/home/bs/.bun/bin/omp")
LOG_DIR = Path(os.environ.get("MULTICA_OMP_LOG_DIR", "/tmp"))

AGENTS_MARKER_BEGIN = "<!-- BEGIN MULTICA-AUTO-AGENTS-MD (regenerated every run, do not hand-edit) -->"
AGENTS_MARKER_END = "<!-- END MULTICA-AUTO-AGENTS-MD -->"

COMPACT_SCRIPT = os.environ.get(
    "MULTICA_OMP_COMPACT_SCRIPT",
    str(Path(__file__).resolve().parent / "omp-compact.sh"),
)
COMPACT_MAX_ATTEMPTS = 3  # 1 initial try + 2 retries, then fall back uncompacted
COMPACT_RETRY_BACKOFF_SECONDS = 2
COMPACT_PROMPT_TEMPLATE = (
    "Retain details related to unresolved bugs, remaining tasks and the "
    "following user prompt: {user_prompt}"
)
# If the user's prompt contains this keyword, compaction is forced — it
# runs even if the session is under the token threshold, or hasn't grown
# enough since the last compaction to normally warrant another one.
COMPACT_KEYWORD = "/compact"
# Don't recompact just because the file crossed the threshold again by a
# hair — require it to have grown by at least this many estimated tokens
# since the last compaction before we bother doing it again.
COMPACT_MIN_GROWTH_TOKENS = int(
    os.environ.get("MULTICA_OMP_COMPACT_MIN_GROWTH_TOKENS", "15000")
)

# ---------------------------------------------------------------------------
# Runtime profiles — one source of truth instead of three bash files
# ---------------------------------------------------------------------------

PROFILES = {
    # Leaders: orchestrate only, no reasoning/coding tools.
    "smol": {
        "approval-mode": "write",
        "tools": "read,grep,glop,web-search,bash",
        "extra_flags": ["--no-title", "--no-lsp", "--no-pty"],
        "thinking": "medium",
        "max-time": "30m",
    },
    # Workers: reasoning + documenting, can write/edit/plan but not execute code.
    "reasoning": {
        "approval-mode": "yolo",
        "tools": "read,grep,glop,web-search,bash,write,edit,task,todo",
        "extra_flags": ["--no-title", "--no-lsp", "--no-pty"],
        "thinking": "max",
        "max-time": "120m",
    },
    # Coding/testing agents: full tool access including python + lsp.
    "coding": {
        "approval-mode": "yolo",
        "tools": "read,grep,glop,web-search,bash,write,edit,task,todo,python,lsp",
        "extra_flags": ["--no-title", "--no-pty"],
        "thinking": "max",
        "max-time": "120m",
    },
    # Passthrough: the caller (e.g. a shim generated by
    # add-multica-omp-runtime.sh) already fully specifies its own omp flags
    # and only wants this wrapper's side effects — logging, CLAUDE.md/
    # AGENTS.md merging, and session compaction — with nothing forced or
    # overridden.
    "passthrough": {
        "approval-mode": None,
        "tools": None,
        "extra_flags": [],
        "thinking": None,
        "max-time": None,
    },
}

PROFILE_ALIASES = {
    "multica-omp-smol": "smol",
    "multica-omp-reasoning": "reasoning",
    "multica-omp-coding": "coding",
}


def detect_profile(explicit: str | None) -> str | None:
    if explicit:
        return explicit
    env = os.environ.get("MULTICA_OMP_PROFILE")
    if env:
        return env
    base = Path(sys.argv[0]).name
    if base in PROFILE_ALIASES:
        return PROFILE_ALIASES[base]
    if base in PROFILES:
        return base
    return None


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

def log_call(profile: str, session: str | None, args: list[str]) -> None:
    log_file = LOG_DIR / f"multica_omp_{profile}_args.log"
    ts = time.strftime("%Y-%m-%dT%H:%M:%S%z")
    with log_file.open("a", encoding="utf-8") as fh:
        fh.write(f"[{ts}] profile={profile} session={session} pid={os.getpid()}\n")
        fh.write(" ".join(args) + "\n")
        fh.write("-" * 47 + " END OF LOG " + "-" * 47 + "\n")


def extract_flag_value(args: list[str], flag: str) -> str | None:
    for i, a in enumerate(args):
        if a == flag and i + 1 < len(args):
            return args[i + 1]
        if a.startswith(flag + "="):
            return a.split("=", 1)[1]
    return None


# ---------------------------------------------------------------------------
# CLAUDE.md / AGENTS.md shadowing fix
# ---------------------------------------------------------------------------

def backup_claude_md(project_dir: Path) -> tuple[Path | None, bool]:
    """Create a backup of CLAUDE.md before we mutate it.

    Returns:
      (backup_path, had_original)
        - backup_path is None if CLAUDE.md did not exist.
        - had_original indicates whether CLAUDE.md existed pre-run.
    """
    claude_md = project_dir / "CLAUDE.md"
    if not claude_md.exists():
        return None, False

    backup_path = project_dir / f"CLAUDE.md.multica-omp-backup.{os.getpid()}.{uuid.uuid4().hex}"
    shutil.copy2(claude_md, backup_path)
    return backup_path, True


def restore_claude_md(
    project_dir: Path,
    backup_path: Path | None,
    had_original: bool,
) -> None:
    """Restore CLAUDE.md to its exact pre-run state."""
    claude_md = project_dir / "CLAUDE.md"

    if had_original:
        if backup_path and backup_path.exists():
            shutil.move(str(backup_path), str(claude_md))
        return

    # CLAUDE.md did not exist before this run. If merge created one, remove it.
    if claude_md.exists():
        claude_md.unlink()



def merge_agents_into_claude(project_dir: Path) -> None:
    """Append AGENTS.md into CLAUDE.md (idempotently) and hide AGENTS.md.

    Safe to call even if a previous run crashed mid-flight: if we find
    AGENTS.md.ignored but no AGENTS.md, we self-heal by restoring first,
    then redo the merge fresh so CLAUDE.md picks up the latest content.
    """
    agents_md = project_dir / "AGENTS.md"
    agents_hidden = project_dir / "AGENTS.md.ignored"
    claude_md = project_dir / "CLAUDE.md"

    if agents_hidden.exists() and not agents_md.exists():
        agents_hidden.rename(agents_md)

    if not agents_md.exists():
        return  # nothing generated this run, nothing to do

    agents_content = agents_md.read_text(encoding="utf-8").rstrip()
    block = f"{AGENTS_MARKER_BEGIN}\n{agents_content}\n{AGENTS_MARKER_END}\n"

    if claude_md.exists():
        existing = claude_md.read_text(encoding="utf-8")
        if AGENTS_MARKER_BEGIN in existing and AGENTS_MARKER_END in existing:
            pre, _, rest = existing.partition(AGENTS_MARKER_BEGIN)
            _, _, post = rest.partition(AGENTS_MARKER_END)
            new_content = pre.rstrip("\n") + "\n\n" + block + post.lstrip("\n")
        else:
            sep = "" if not existing or existing.endswith("\n\n") else (
                "\n" if existing.endswith("\n") else "\n\n"
            )
            new_content = existing + sep + block
    else:
        new_content = block

    claude_md.write_text(new_content, encoding="utf-8")
    agents_md.rename(agents_hidden)


def restore_agents_md(project_dir: Path) -> None:
    agents_md = project_dir / "AGENTS.md"
    agents_hidden = project_dir / "AGENTS.md.ignored"
    if agents_hidden.exists() and not agents_md.exists():
        agents_hidden.rename(agents_md)


# ---------------------------------------------------------------------------
# Context compaction for resumed sessions
# ---------------------------------------------------------------------------

def estimate_tokens(session_path: Path) -> int:
    """Very rough token estimate (chars / 4) over a .jsonl session file.

    This is deliberately crude — no tokenizer dependency — good enough to
    trip a threshold, not to give an exact count.
    """
    total_chars = 0
    try:
        with session_path.open("r", encoding="utf-8") as fh:
            for line in fh:
                try:
                    obj = json.loads(line)
                except json.JSONDecodeError:
                    total_chars += len(line)
                    continue
                total_chars += len(json.dumps(obj))
    except FileNotFoundError:
        return 0
    return total_chars // 4


def _compaction_log(msg: str) -> None:
    log_file = LOG_DIR / "multica_omp_compaction.log"
    ts = time.strftime("%Y-%m-%dT%H:%M:%S%z")
    with log_file.open("a", encoding="utf-8") as fh:
        fh.write(f"[{ts}] {msg}\n")
    print(f"multica-omp-wrapper[compaction]: {msg}", file=sys.stderr)


def _state_path(session_path: Path) -> Path:
    return session_path.with_suffix(session_path.suffix + ".compaction-state.json")


def _load_last_compaction_tokens(session_path: Path) -> int | None:
    state_file = _state_path(session_path)
    try:
        data = json.loads(state_file.read_text(encoding="utf-8"))
        return int(data.get("tokens_after_compaction"))
    except (FileNotFoundError, json.JSONDecodeError, TypeError, ValueError):
        return None


def _save_compaction_state(session_path: Path, tokens_after: int, script_data: dict) -> None:
    state_file = _state_path(session_path)
    state_file.write_text(
        json.dumps(
            {
                "tokens_after_compaction": tokens_after,
                "tokens_before_compaction": script_data.get("tokensBefore"),
                "compacted_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
            }
        ),
        encoding="utf-8",
    )


def _find_first_user_message(lines: list[str]) -> tuple[int, str] | None:
    """Return (index, id) of the first `type: message, role: user` line."""
    for i, raw in enumerate(lines):
        try:
            obj = json.loads(raw)
        except json.JSONDecodeError:
            continue
        if obj.get("type") == "message":
            message = obj.get("message") or {}
            if message.get("role") == "user":
                return i, obj.get("id", "")
    return None


def _run_compact_script(prompt: str, session_copy: Path, provider: str, model: str) -> dict | None:
    """Invoke omp-compact.sh once and return validated `data`, or None."""
    script = COMPACT_SCRIPT
    cmd = [script] if os.access(script, os.X_OK) else ["bash", script]
    cmd += [prompt, "--session", str(session_copy), "--provider", provider, "--model", model]

    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
    except (subprocess.TimeoutExpired, OSError) as exc:
        _compaction_log(f"omp-compact.sh invocation failed: {exc}")
        return None

    if proc.returncode != 0:
        _compaction_log(
            f"omp-compact.sh exited {proc.returncode}; stderr={proc.stderr.strip()[:500]!r}"
        )
        return None

    try:
        parsed = json.loads(proc.stdout.strip())
    except json.JSONDecodeError:
        _compaction_log(f"omp-compact.sh returned non-JSON stdout: {proc.stdout.strip()[:500]!r}")
        return None

    if not (
        parsed.get("type") == "response"
        and parsed.get("command") == "compact"
        and parsed.get("success") is True
        and isinstance(parsed.get("data"), dict)
        and parsed["data"].get("summary")
    ):
        _compaction_log(f"omp-compact.sh returned an unexpected shape: {parsed!r}")
        return None

    return parsed["data"]


def maybe_compact_session(
    session: str | None,
    threshold_tokens: int,
    profile: str,
    args: list[str],
) -> None:
    """Compact `session` in place if it's grown large, with retries and a
    safe uncompacted fallback if anything looks wrong at any step.

    Compaction is also forced — bypassing the token threshold and the
    min-growth-since-last-compaction guard — whenever the user's prompt
    contains `COMPACT_KEYWORD` (e.g. "/compact").
    """
    if not session:
        return
    session_path = Path(session)
    tokens = estimate_tokens(session_path)
    user_prompt = args[-1] if args else ""
    forced = COMPACT_KEYWORD in user_prompt

    if not forced and tokens < threshold_tokens:
        return

    last_compacted_tokens = _load_last_compaction_tokens(session_path)
    if (
        not forced
        and last_compacted_tokens is not None
        and tokens - last_compacted_tokens < COMPACT_MIN_GROWTH_TOKENS
    ):
        _compaction_log(
            f"session={session} est_tokens~={tokens} is over threshold but has only "
            f"grown by {tokens - last_compacted_tokens} tokens since the last "
            f"compaction (min growth {COMPACT_MIN_GROWTH_TOKENS}); skipping for now"
        )
        return

    provider = extract_flag_value(args, "--provider") or "bifrost"
    model = extract_flag_value(args, "--model") or ""
    if forced:
        user_prompt = user_prompt.replace(COMPACT_KEYWORD, "").strip()
    prompt = COMPACT_PROMPT_TEMPLATE.format(user_prompt=user_prompt)

    reason = (
        f"'{COMPACT_KEYWORD}' keyword in prompt"
        if forced
        else f"est_tokens~={tokens} >= threshold={threshold_tokens}"
    )
    _compaction_log(
        f"session={session} {reason}; attempting compaction (profile={profile})"
    )

    try:
        original_lines = session_path.read_text(encoding="utf-8").splitlines(keepends=True)
    except FileNotFoundError:
        _compaction_log(f"session={session} vanished before compaction could read it; skipping")
        return

    anchor = _find_first_user_message(original_lines)
    if anchor is None:
        _compaction_log(
            f"session={session} has no `type: message, role: user` line; "
            f"cannot safely truncate, skipping compaction"
        )
        return
    anchor_idx, anchor_id = anchor

    backup_dir = session_path.parent / "compacted-backups"
    backup_dir.mkdir(exist_ok=True)
    backup_path = backup_dir / f"{session_path.stem}.{int(time.time())}.jsonl"
    shutil.copy2(session_path, backup_path)

    session_copy = session_path.with_suffix(session_path.suffix + ".compact-tmp")
    shutil.copy2(session_path, session_copy)

    data = None
    try:
        for attempt in range(1, COMPACT_MAX_ATTEMPTS + 1):
            data = _run_compact_script(prompt, session_copy, provider, model)
            if data is not None:
                break
            _compaction_log(f"compaction attempt {attempt}/{COMPACT_MAX_ATTEMPTS} failed")
            if attempt < COMPACT_MAX_ATTEMPTS:
                time.sleep(COMPACT_RETRY_BACKOFF_SECONDS)
    finally:
        session_copy.unlink(missing_ok=True)

    if data is None:
        _compaction_log(
            f"all {COMPACT_MAX_ATTEMPTS} compaction attempts failed for session={session}; "
            f"falling back to the uncompacted session (backup kept at {backup_path})"
        )
        return

    script_first_kept = data.get("firstKeptEntryId")
    if script_first_kept and script_first_kept != anchor_id:
        _compaction_log(
            f"note: omp-compact.sh's firstKeptEntryId={script_first_kept!r} differs from "
            f"the first user message id we detected ({anchor_id!r}); using our own, since "
            f"that's the id actually present in the lines we're keeping"
        )

    summary_line = {
        "type": "message",
        "id": uuid.uuid4().hex[:8],
        "parentId": anchor_id,
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S.000Z", time.gmtime()),
        "message": {
            "role": "assistant",
            "content": [{"type": "text", "text": data["summary"]}],
            "attribution": "compaction",
            "timestamp": int(time.time() * 1000),
        },
        "compactionMeta": {
            "shortSummary": data.get("shortSummary"),
            "tokensBefore": data.get("tokensBefore"),
            "sourceCompactId": data.get("id") or parsed_id_fallback(data),
        },
    }

    kept_lines = original_lines[: anchor_idx + 1]
    if kept_lines and not kept_lines[-1].endswith("\n"):
        kept_lines[-1] += "\n"
    new_content = "".join(kept_lines) + json.dumps(summary_line) + "\n"

    tmp_out = session_path.with_suffix(session_path.suffix + ".new-tmp")
    tmp_out.write_text(new_content, encoding="utf-8")
    os.replace(tmp_out, session_path)

    tokens_after = estimate_tokens(session_path)
    _save_compaction_state(session_path, tokens_after, data)
    _compaction_log(
        f"session={session} compacted: kept {anchor_idx + 1} preamble line(s) + 1 summary "
        f"line; tokensBefore={data.get('tokensBefore')} est_tokens_after~={tokens_after} "
        f"(original backed up at {backup_path})"
    )


def parsed_id_fallback(data: dict) -> str | None:
    # omp-compact.sh's own event id (e.g. "compact_1") is not reused as the
    # session line's id — that id isn't guaranteed unique across repeated
    # compactions of the same session — but we keep it here for tracing.
    return None


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--profile", choices=PROFILES.keys(), default=None)
    parser.add_argument("--project-dir", default=os.getcwd())
    parser.add_argument("--compact-threshold-tokens", type=int, default=60000)
    known, omp_args = parser.parse_known_args()

    profile = detect_profile(known.profile)
    if profile not in PROFILES:
        sys.stderr.write(
            f"multica-omp-wrapper: cannot determine profile "
            f"(argv0={sys.argv[0]!r}, MULTICA_OMP_PROFILE unset, no --profile). "
            f"Expected one of: {', '.join(PROFILES)}\n"
        )
        return 2

    spec = PROFILES[profile]
    project_dir = Path(known.project_dir).resolve()
    session = extract_flag_value(omp_args, "--session")

    log_call(profile, session, omp_args)
    maybe_compact_session(session, known.compact_threshold_tokens, profile, omp_args)

    claude_backup_path, claude_had_original = backup_claude_md(project_dir)
    merge_agents_into_claude(project_dir)

    cleaned_up = {"done": False}

    def _cleanup() -> None:
        if cleaned_up["done"]:
            return
        cleaned_up["done"] = True
        restore_agents_md(project_dir)
        restore_claude_md(project_dir, claude_backup_path, claude_had_original)

    atexit.register(_cleanup)

    def _on_signal(signum, _frame):
        _cleanup()
        sys.exit(128 + signum)

    signal.signal(signal.SIGTERM, _on_signal)
    signal.signal(signal.SIGINT, _on_signal)

    cmd = [OMP_BIN]
    if spec.get("approval-mode"):
        cmd += ["--approval-mode", spec["approval-mode"]]
    if spec.get("tools"):
        cmd += ["--tools", spec["tools"]]
    if spec.get("thinking"):
        cmd += ["--thinking", spec["thinking"]]
    if spec.get("max-time"):
        cmd += ["--max-time", spec["max-time"]]
    cmd += spec.get("extra_flags", [])
    cmd += omp_args

    try:
        result = subprocess.run(cmd)
        return result.returncode
    finally:
        _cleanup()


if __name__ == "__main__":
    sys.exit(main())
